n = input('Coloque algo para prosseguir por gentileza: ')
print('O tipo do seu termo é', type(n))
print(' o seu numero contem espaços?', n.isspace())
print(' é um numero?', n.isnumeric())
print("é alfabetico?", n.isalpha())
print('possi letras e numeros?', n.isalnum())
print('esta em letras maiusculas?', n.isupper())
print('ta em letras minusculas?', n.islower())
print('tem letras maiusculas e minusculas?', n.istitle())